[package]
name = "firebase-rs"
edition = "2021"
version = "2.0.0"
description = "Rust based Firebase library"
readme = "README.md"
repository = "https://github.com/emreyalvac/firebase-rs"
documentation = "https://docs.rs/firebase-rs/1.0.3/firebase_rs/"
license = "MIT"
authors = ["Emre YALVAÇ <emre.yalvac@outlook.com>"]
exclude = ["examples/*", "tests/*"]
keywords = ["firebase", "rest", "api", "web", "database"]

[dependencies]
url = "2.2.2"
reqwest = { version = "0.11.7", features = ["json"] }
serde_json = "1.0.73"
serde = { version = "1.0.132", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.14.0", features = ["rt", "macros"] }
